final List<String> allReasons = [
  "Work",
  "School & Studies",
  "Deadlines",
  "Productivity",
  "Coworkers",
  "Family",
  "Friends",
  "Relationship",
  "Socializing",
  "Conflict",
  "Loneliness",
  "Sleep",
  "Exercise",
  "Hobby & Play",
  "Food & Diet",
  "Chores & Errands",
  "Commute",
  "Physical Health",
  "Mental Well-being",
  "Stress",
  "Anxiety",
  "Relaxation",
  "Self-Care",
  "Travel & Outing",
  "Weather",
  "Pets",
  "Entertainment",
  "Finances",
  "Personal Growth",
  "Success & Milestone",
  "Setbacks",
  "Future Plans"
];